# Continuous integration, including test and integration test
name: CI

# Run in master and dev branches and in all pull requests to those branches
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  DOCKER_IMAGE: radarbase/radar-output-restructure

jobs:
  # Build and test the code
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - uses: gradle/gradle-build-action@v2

      - name: Decrypt libraries
        run: ./.github/scripts/decrypt_libraries.sh
        env:
          E4LINK_PASSPHRASE: ${{ secrets.E4LINK_PASSPHRASE }}

      # Compile the code
      - name: Compile code
        run: ./gradlew assembleDebug

      # Gradle check
      - name: Check
        run: ./gradlew testDebugUnitTest lintDebug
